
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emreyazici
 */
public class GameF extends javax.swing.JFrame {

    /**
     * Creates new form GameF
     */
    //player ve manager oluştur aşağıda constructer içinde bunları this ile eşitle
    private Player player;
    private Manager manager;
    private JButton[] btnsMap = new JButton[32];
    private ImageIcon iconTreasure;
    private ImageIcon iconTrap;
    private ImageIcon iconCharacter;
    private ImageIcon iconFinishFlag;
    public GameF(Player player,Manager manager) {
        this.player=player;
        this.manager=manager;
        this.iconTreasure = new ImageIcon(getClass().getResource("/images/treasureBtn.png"));
        this.iconTrap = new ImageIcon(getClass().getResource("/images/dang1.png"));
        this.iconCharacter = new ImageIcon(getClass().getResource("/images/miner.png"));
        this.iconFinishFlag = new ImageIcon(getClass().getResource("/images/finish.png"));
        
        if (player.getLevel()==1) {
            manager.createMapFirstLevel();
        }else{
            manager.createMapFirstLevel();
        }
        initComponents();
        setLayout(new BorderLayout());
        panelMap.setLayout(new GridLayout(4, 8, 12, 12));
        
        for (int i = 0; i < 32; i++) {
            btnsMap[i]=new JButton(String.valueOf(i));
            btnsMap[i].setHorizontalTextPosition(JButton.CENTER);
            btnsMap[i].setVerticalTextPosition(JButton.BOTTOM);
            btnsMap[i].setHorizontalAlignment(JButton.CENTER);
            panelMap.add(btnsMap[i]);
        }
        setButonIcons();
    }
    
    private void setButonIcons(){
        int i=0;
        SNode temp = manager.getsListFirstLevel().getHeader();
        while (temp!=null && i<32) {            
            if (temp.getSpotType()=="Start") {
                btnsMap[i].setIcon(iconCharacter);
            }else if (temp.getSpotType()=="Finish") {
                btnsMap[i].setIcon(iconFinishFlag);
            }else if (temp.getSpotType()=="Treasure") {
                btnsMap[i].setIcon(iconTreasure);
                btnsMap[i].setBackground(new Color(139,69,19)); // Goldenrod koyu sarı
            }else if (temp.getSpotType()=="Trap") {
                btnsMap[i].setIcon(iconTrap);
                btnsMap[i].setBackground(new Color(105, 105, 105
));
            }else
                btnsMap[i].setBackground(new Color(240, 248, 255));

            temp=temp.getNext();
            i++;
        }
        btnsMap[31].setIcon(iconFinishFlag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMap = new javax.swing.JPanel();
        panelInfos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelMapLayout = new javax.swing.GroupLayout(panelMap);
        panelMap.setLayout(panelMapLayout);
        panelMapLayout.setHorizontalGroup(
            panelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        panelMapLayout.setVerticalGroup(
            panelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelInfosLayout = new javax.swing.GroupLayout(panelInfos);
        panelInfos.setLayout(panelInfosLayout);
        panelInfosLayout.setHorizontalGroup(
            panelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInfosLayout.setVerticalGroup(
            panelInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                try { 
//                    new GameF(player, manager).setVisible(true);
//                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(null, "null player or manager!!!");
//                }
                //new GameF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelInfos;
    private javax.swing.JPanel panelMap;
    // End of variables declaration//GEN-END:variables
}
